Odkazy:
  Discord_URL: "https://discord.gg/TVUJ_SERVER"
  YouTube_URL: "https://youtube.com/TVUJ_KANAL"
  Obchod_URL: "https://obchod.TVUJ_SERVER.cz"

Zpravy:
  Discord_Zprava: "Klikni pro náš Discord!"
  YouTube_Zprava: "Odeber náš YouTube kanál!"
  Obchod_Zprava: "Podpoř server na našem obchodě!"

Systemove_Zpravy:
  Pouze_Hrac: "§cTento příkaz mohou používat pouze hráči."

  Prefix_Discord: "§9DISCORD"
  Prefix_YouTube: "§cYOUTUBE"
  Prefix_Obchod: "§6OBCHOD"
